### ISSUE TITLE
TMC CONNECTION ERROR after booting

### ISSUE THREAD

**Issue by fooandbar** [fooandbar/Mks-Robin-Nano-Marlin2.0-Firmware-For-Selpic-Star-A.LABISTS-SX1#1]
### Description
after booting up, I get an error message on the LCD and the error is also printed on the console (see attachment).

### Steps to Reproduce

1. Power on

**Expected behavior:** [What you expect to happen]
no error.

**Actual behavior:** [What actually happens]
I get an error message on the LCD and the error is also printed on the console (see attachment).
![error](https://user-images.githubusercontent.com/63621440/117113937-245aea80-adc6-11eb-8bdc-8596876a378b.jpg)

#### Additional Information
[error.txt](https://github.com/fooandbar/Mks-Robin-Nano-Marlin2.0-Firmware-For-Selpic-Star-A.LABISTS-SX1/files/6425831/error.txt)

**Comment by christianscharr** [comment]
Is this bug still open? You said you got it working on kickstarter...
If its still existing try to reduce the baudrate on the serial port communication... Saw some discussions on similiar Marlin related discussions which suggested to do so to enhance reliabilty while using tmc steppers. I dont know what type of steppers are built-in on the star a, but its worse a try ;)

`// Reduce baud rate to improve reliability
 #if HAS_TMC_SW_SERIAL
   #define TMC_BAUD_RATE 19200`

**Comment by fooandbar** [comment]
Thanks for following the bug. I got an error once at startup, but since there is no problem after that, I left this bug.
I reduced the baud rate to 9600, but the result was the same.

**Comment by fooandbar** [comment]
`M122` reports an registor error, so I disable TMC options.
